# Generated by Django 5.2.9 on 2026-01-04 17:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('order', models.PositiveIntegerField(help_text='Order in simulation', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['simulation', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DialogueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('text', models.TextField()),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='simulator.dialogue')),
            ],
            options={
                'ordering': ['dialogue', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LineRecording',
            fields=[
                ('dialogue_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recording', serialize=False, to='simulator.dialogueline')),
                ('audio_file', models.FileField(upload_to='simulations/lines/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(help_text="Character name (e.g., 'Marie', 'Waiter')", max_length=100)),
                ('is_system', models.BooleanField(default=False, help_text='System auto-generates TTS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'speaker_name'],
            },
        ),
        migrations.AddField(
            model_name='dialogueline',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='simulator.participant'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='participants',
            field=models.ManyToManyField(related_name='dialogues', to='simulator.participant'),
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('current_line', models.PositiveIntegerField(default=1)),
                ('final_audio', models.FileField(blank=True, null=True, upload_to='simulations/final/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_dialogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_simulations', to='simulator.dialogue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dialogue',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='simulator.simulation'),
        ),
        migrations.AlterUniqueTogether(
            name='dialogueline',
            unique_together={('dialogue', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='dialogue',
            unique_together={('simulation', 'order')},
        ),
    ]
