# Generated by Django 5.2.10 on 2026-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='complete_audio',
            field=models.FileField(blank=True, null=True, upload_to='dialogues/complete/'),
        ),
    ]
